export type Category =
  | 'wigs'
  | 'bundles'
  | 'custom-wigs'
  | 'maintenance'
  | 'beauty'
  | 'coats'

export interface Product {
  id: string
  name: string
  slug: string
  category: Category
  categoryLabel: string
  price: number        // USD base price
  originalPrice?: number
  images: string[]
  video?: string       // YouTube video ID or full URL (shows hair movement)
  badge?: 'new' | 'sale' | 'hot' | 'bestseller'
  description: string
  shortDesc: string
  features: string[]
  variants?: { label: string; options: string[] }[]
  inStock: boolean
  stockCount?: number  // show "Only X left" when low
  weightKg: number
  rating: number
  reviews: number
  shipsFrom: string
  deliveryDays: string
  tags: string[]
}

export const EXCHANGE_RATES = { NGN: 1620, GHS: 16.2, USD: 1, CNY: 7.25 }

export function formatPrice(usd: number, currency: 'NGN' | 'GHS' | 'USD' | 'CNY'): string {
  const amount = usd * EXCHANGE_RATES[currency]
  if (currency === 'NGN') return `₦${amount.toLocaleString('en-NG', { maximumFractionDigits: 0 })}`
  if (currency === 'GHS') return `GH₵${amount.toLocaleString('en-GH', { maximumFractionDigits: 0 })}`
  if (currency === 'CNY') return `¥${amount.toFixed(2)}`
  return `$${amount.toFixed(2)}`
}

export const products: Product[] = [
  // ── WIGS ──────────────────────────────────────────────────────────────────
  {
    id: 'wig-001',
    name: 'Brazilian Straight HD Lace Front Wig',
    slug: 'brazilian-straight-hd-lace-front',
    category: 'wigs',
    categoryLabel: 'Human Hair Wigs',
    price: 189,
    originalPrice: 240,
    images: [
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=80',
    ],
    video: 'https://www.youtube.com/embed/dDrpDkTcFss',
    badge: 'bestseller',
    shortDesc: '100% virgin Brazilian human hair. HD lace for undetectable hairline.',
    description: 'Experience the ultimate in luxury with our Brazilian Straight HD Lace Front Wig. Crafted from 100% virgin human hair, this wig features an ultra-thin HD lace that melts seamlessly into any skin tone for a completely natural, undetectable hairline. Perfect for queens who demand the best.',
    features: [
      '100% Virgin Brazilian Human Hair',
      'HD Transparent Lace – melts into skin',
      'Pre-plucked hairline with baby hair',
      'Available 12"–30" lengths',
      '150% / 180% / 250% density options',
      'Can be dyed, bleached & heat-styled',
      'Adjustable cap with combs & straps',
    ],
    variants: [
      { label: 'Length', options: ['12"', '14"', '16"', '18"', '20"', '22"', '24"', '26"', '28"', '30"'] },
      { label: 'Density', options: ['150%', '180%', '250%'] },
      { label: 'Cap Size', options: ['Small (21")', 'Medium (22")', 'Large (23")'] },
    ],
    inStock: true,
    weightKg: 0.35,
    rating: 4.9,
    reviews: 247,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['straight', 'lace front', 'brazilian', 'hd lace'],
  },
  {
    id: 'wig-002',
    name: 'Deep Wave Full Lace Wig',
    slug: 'deep-wave-full-lace-wig',
    category: 'wigs',
    categoryLabel: 'Human Hair Wigs',
    price: 215,
    originalPrice: 280,
    images: [
      'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?auto=format&fit=crop&w=800&q=80',
    ],
    video: 'https://www.youtube.com/embed/AioSHE9Zv2w',
    badge: 'hot',
    shortDesc: 'Stunning deep wave pattern. Full lace for versatile parting.',
    description: 'Turn heads with our Deep Wave Full Lace Wig — luscious, bouncy waves that command attention. Full lace construction allows you to part anywhere, pull up into a ponytail, or style as you please. 100% human hair responds beautifully to heat and moisture.',
    features: [
      '100% Virgin Human Hair',
      'Full lace cap – part anywhere',
      'Natural deep wave pattern',
      'Wet & wavy when activated with water',
      '130% – 200% density',
      'Pre-plucked with baby hair',
      'Swiss lace base',
    ],
    variants: [
      { label: 'Length', options: ['14"', '16"', '18"', '20"', '22"', '24"', '26"'] },
      { label: 'Density', options: ['130%', '150%', '180%', '200%'] },
    ],
    inStock: true,
    weightKg: 0.35,
    rating: 4.8,
    reviews: 183,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['deep wave', 'full lace', 'curly', 'human hair'],
  },
  {
    id: 'wig-003',
    name: 'Kinky Curly 5x5 Closure Wig',
    slug: 'kinky-curly-5x5-closure-wig',
    category: 'wigs',
    categoryLabel: 'Human Hair Wigs',
    price: 165,
    originalPrice: 210,
    images: [
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'new',
    shortDesc: 'Embrace your natural roots. Kinky curly perfection.',
    description: 'Celebrate the beauty of natural texture with our Kinky Curly 5×5 HD Closure Wig. This stunning wig delivers voluminous, defined curls that mirror your natural hair. The 5×5 HD lace closure provides a generous parting space for the most natural-looking styles.',
    features: [
      '100% Virgin Kinky Curly Human Hair',
      '5×5 HD Transparent Lace Closure',
      'Natural 4A/4B curl pattern',
      'Pre-plucked natural hairline',
      'Glueless wear option',
      'Can co-wash and refresh curls',
      '180% density',
    ],
    variants: [
      { label: 'Length', options: ['12"', '14"', '16"', '18"', '20"', '22"'] },
      { label: 'Density', options: ['150%', '180%', '200%'] },
    ],
    inStock: true,
    weightKg: 0.35,
    rating: 4.7,
    reviews: 129,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['kinky curly', 'natural', 'afro', 'closure wig'],
  },
  {
    id: 'wig-004',
    name: 'Bone Straight 13x4 Lace Frontal Wig',
    slug: 'bone-straight-13x4-lace-frontal',
    category: 'wigs',
    categoryLabel: 'Human Hair Wigs',
    price: 198,
    images: [
      'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1574015974293-817f0ebebb74?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'hot',
    shortDesc: 'Silky bone straight perfection. 13x4 frontal for dramatic parting.',
    description: 'Our Bone Straight 13×4 Lace Frontal Wig is sleek, glossy perfection. The ultra-smooth texture lies pin-straight for a super polished look. The generous 13×4 frontal coverage gives you maximum styling flexibility from ear to ear.',
    features: [
      '100% Bone Straight Human Hair',
      '13×4 Transparent HD Lace Frontal',
      'Zero shed, zero tangle',
      'Silky smooth texture',
      'Available up to 40" length',
      'Can be coloured and heat-styled',
    ],
    variants: [
      { label: 'Length', options: ['14"', '16"', '18"', '20"', '22"', '24"', '26"', '28"', '30"', '32"', '34"', '36"', '40"'] },
      { label: 'Density', options: ['150%', '180%', '250%'] },
    ],
    inStock: true,
    weightKg: 0.35,
    rating: 4.9,
    reviews: 312,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['bone straight', '13x4', 'frontal', 'sleek'],
  },
  {
    id: 'wig-005',
    name: 'Body Wave Glueless Wig',
    slug: 'body-wave-glueless-wig',
    category: 'wigs',
    categoryLabel: 'Human Hair Wigs',
    price: 175,
    originalPrice: 220,
    images: [
      'https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'sale',
    shortDesc: 'Effortless glamour. No glue needed — wear & go.',
    description: 'Our Body Wave Glueless Wig is designed for the queen on the go. The elastic band + combs secure this wig perfectly without any glue or adhesive. Gorgeous S-wave pattern adds fullness and movement for every occasion.',
    features: [
      '100% Human Hair Body Wave',
      'True glueless – elastic band + combs',
      'Pre-bleached knots',
      'Natural S-wave body movement',
      'Beginner friendly',
      'Ready to wear in minutes',
    ],
    variants: [
      { label: 'Length', options: ['12"', '14"', '16"', '18"', '20"', '22"', '24"'] },
      { label: 'Density', options: ['150%', '180%'] },
    ],
    inStock: true,
    weightKg: 0.35,
    rating: 4.8,
    reviews: 198,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['body wave', 'glueless', 'beginner', 'wear and go'],
  },

  // ── BUNDLES ───────────────────────────────────────────────────────────────
  {
    id: 'bundle-001',
    name: 'Brazilian Body Wave 3 Bundle Deal',
    slug: 'brazilian-body-wave-3-bundle',
    category: 'bundles',
    categoryLabel: 'Hair Bundles',
    price: 135,
    originalPrice: 185,
    images: [
      'https://images.unsplash.com/photo-1522338140262-f46f5913618a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1556228852-80b6e5eeff06?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'bestseller',
    shortDesc: '3 bundles of 100% Brazilian body wave. Full, luscious volume.',
    description: 'Our bestselling Brazilian Body Wave Bundle Deal gives you everything you need for a full, voluminous install. Three bundles of premium 100% virgin human hair with a natural wave pattern that\'s beautiful wet or dry. Pairs perfectly with our closure or frontal pieces.',
    features: [
      '3 Bundles (100g each)',
      '100% Virgin Brazilian Human Hair',
      'Natural body wave pattern',
      'Can be coloured and heat styled',
      'Double weft construction',
      'Minimal shedding, no tangling',
      'Natural black colour (1B)',
    ],
    variants: [
      { label: 'Length Combo', options: ['10/12/14"', '12/14/16"', '14/16/18"', '16/18/20"', '18/20/22"', '20/22/24"', '22/24/26"'] },
    ],
    inStock: true,
    weightKg: 0.15,
    rating: 4.9,
    reviews: 421,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['bundles', 'body wave', 'brazilian', '3 bundle deal'],
  },
  {
    id: 'bundle-002',
    name: 'Peruvian Straight 4 Bundle + Closure',
    slug: 'peruvian-straight-4-bundle-closure',
    category: 'bundles',
    categoryLabel: 'Hair Bundles',
    price: 195,
    originalPrice: 260,
    images: [
      'https://images.unsplash.com/photo-1556228852-80b6e5eeff06?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'hot',
    shortDesc: '4 bundles + free 4x4 closure. Complete install kit.',
    description: 'The ultimate installation bundle. Four Peruvian straight bundles with a matching 4×4 HD lace closure included — everything for a seamless full sew-in. Peruvian hair is prized for its fine, silky texture and natural lustre.',
    features: [
      '4 Bundles + 4×4 HD Closure FREE',
      '100% Virgin Peruvian Human Hair',
      'Silky straight texture',
      'Fine, lightweight feel',
      'Colour: Natural Black (1B)',
      'Can be coloured to #613 blonde',
    ],
    variants: [
      { label: 'Length Combo', options: ['12/14/16/18"', '14/16/18/20"', '16/18/20/22"', '18/20/22/24"', '20/22/24/26"'] },
    ],
    inStock: true,
    weightKg: 0.15,
    rating: 4.8,
    reviews: 287,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['peruvian', 'straight', '4 bundle', 'closure included'],
  },
  {
    id: 'bundle-003',
    name: 'Malaysian Curly 3 Bundle Deal',
    slug: 'malaysian-curly-3-bundle',
    category: 'bundles',
    categoryLabel: 'Hair Bundles',
    price: 148,
    originalPrice: 190,
    images: [
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'new',
    shortDesc: 'Bouncy Malaysian curls. Thick, full, and lustrous.',
    description: 'Malaysian hair is renowned for its incredible thickness and lustre. Our Malaysian Curly bundles deliver gorgeous, springy curls that hold their shape beautifully. Naturally glossy with a stunning curl pattern that photographs like a dream.',
    features: [
      '3 Bundles (100g each)',
      '100% Virgin Malaysian Human Hair',
      'Natural curly pattern',
      'Extra thick & lustrous texture',
      'Minimal maintenance required',
      'Excellent curl retention',
    ],
    variants: [
      { label: 'Length Combo', options: ['10/12/14"', '12/14/16"', '14/16/18"', '16/18/20"', '18/20/22"'] },
    ],
    inStock: true,
    weightKg: 0.15,
    rating: 4.7,
    reviews: 156,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['malaysian', 'curly', 'bundles', 'thick'],
  },

  // ── CUSTOM WIGS ───────────────────────────────────────────────────────────
  {
    id: 'custom-001',
    name: 'Custom Made Glueless Wig',
    slug: 'custom-made-glueless-wig',
    category: 'custom-wigs',
    categoryLabel: 'Custom Made Wigs',
    price: 320,
    images: [
      'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'hot',
    shortDesc: 'Handcrafted to your exact measurements. Your wig, your rules.',
    description: 'The pinnacle of personalisation. Our master wig makers construct each custom wig from scratch using your exact head measurements, preferred hair texture, length, density, and colour. Every single strand is hand-tied with precision for the most natural result possible.',
    features: [
      'Hand-crafted from your measurements',
      'Any texture, length, density & colour',
      'HD or Swiss lace options',
      '10–14 day production time',
      'Glueless or adhesive wear',
      'Includes styling guide',
      '6-month quality guarantee',
    ],
    variants: [
      { label: 'Hair Texture', options: ['Straight', 'Body Wave', 'Deep Wave', 'Kinky Curly', 'Loose Curl', 'Water Wave'] },
      { label: 'Lace Type', options: ['HD Transparent Lace', 'Swiss Lace', 'Regular Lace'] },
      { label: 'Length', options: ['10"', '12"', '14"', '16"', '18"', '20"', '22"', '24"', '26"', '28"', '30"'] },
      { label: 'Density', options: ['130%', '150%', '180%', '200%', '250%'] },
    ],
    inStock: true,
    weightKg: 0.4,
    rating: 5.0,
    reviews: 89,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '14–21 business days',
    tags: ['custom', 'bespoke', 'handmade', 'luxury'],
  },
  {
    id: 'custom-002',
    name: 'Custom Coloured Ombre Wig',
    slug: 'custom-coloured-ombre-wig',
    category: 'custom-wigs',
    categoryLabel: 'Custom Made Wigs',
    price: 380,
    images: [
      'https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'new',
    shortDesc: 'Stunning custom colour blends. Bold, beautiful, uniquely yours.',
    description: 'Stand out from the crowd with a custom coloured wig crafted especially for you. Choose your ombre, highlight, or full colour combination. Our colourists use premium hair-safe dyes to achieve stunning results without compromising hair quality.',
    features: [
      'Colour options: ombré, highlights, full colour',
      'Professional hair-safe dyes',
      '100% Virgin Human Hair base',
      'Custom to your specifications',
      'HD lace for invisible hairline',
      '15–20 day production time',
    ],
    variants: [
      { label: 'Colour Style', options: ['Ombre 1B/27', 'Ombre 1B/30', 'Ombre 1B/613', 'Honey Blonde', 'Burgundy', 'Custom Colour'] },
      { label: 'Length', options: ['14"', '16"', '18"', '20"', '22"', '24"', '26"'] },
    ],
    inStock: true,
    weightKg: 0.4,
    rating: 4.9,
    reviews: 62,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '15–25 business days',
    tags: ['coloured', 'ombre', 'custom', 'highlighted'],
  },

  // ── MAINTENANCE ───────────────────────────────────────────────────────────
  {
    id: 'maint-001',
    name: 'Argan Oil Hair Growth Serum',
    slug: 'argan-oil-hair-growth-serum',
    category: 'maintenance',
    categoryLabel: 'Hair Maintenance',
    price: 28,
    originalPrice: 38,
    images: [
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1556228852-80b6e5eeff06?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'bestseller',
    shortDesc: 'Stimulate growth, reduce breakage. 100% natural argan oil blend.',
    description: 'Our Argan Oil Hair Growth Serum is a luxurious blend of pure Moroccan argan oil, biotin, and keratin that penetrates deep into the scalp to stimulate follicles, strengthen strands and combat breakage. Safe for natural hair and wigs.',
    features: [
      '100% Pure Argan Oil base',
      'Biotin + Keratin enriched',
      'Promotes healthy hair growth',
      'Reduces breakage by up to 80%',
      'Safe for coloured & chemically treated hair',
      'Non-greasy formula',
      '50ml bottle',
    ],
    inStock: true,
    weightKg: 0.55,
    rating: 4.8,
    reviews: 312,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['argan oil', 'growth', 'serum', 'scalp'],
  },
  {
    id: 'maint-002',
    name: 'Deep Conditioning Masque',
    slug: 'deep-conditioning-masque',
    category: 'maintenance',
    categoryLabel: 'Hair Maintenance',
    price: 22,
    images: [
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'hot',
    shortDesc: 'Intense moisture treatment. Restore life to dry, damaged hair.',
    description: 'Restore moisture and lustre to dry, over-processed hair with our Deep Conditioning Masque. Infused with shea butter, coconut oil and keratin protein, this rich treatment restores softness and shine in a single use. Perfect for human hair wigs and bundles.',
    features: [
      'Shea butter + Coconut oil + Keratin',
      'Deep penetrating formula',
      'Restores moisture & shine',
      'Reduces frizz by 85%',
      'Perfect for human hair wigs',
      'Use weekly for best results',
      '300ml jar',
    ],
    inStock: true,
    weightKg: 0.55,
    rating: 4.7,
    reviews: 218,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['conditioner', 'mask', 'moisture', 'repair'],
  },
  {
    id: 'maint-003',
    name: 'Protein Repair Treatment',
    slug: 'protein-repair-treatment',
    category: 'maintenance',
    categoryLabel: 'Hair Maintenance',
    price: 32,
    images: [
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'new',
    shortDesc: 'Strengthen and rebuild from within. Professional grade protein.',
    description: 'Our professional-grade Protein Repair Treatment rebuilds the hair\'s internal structure from within. Hydrolysed keratin and silk proteins fill gaps in the cuticle to eliminate breakage, restore elasticity and leave hair feeling incredibly strong.',
    features: [
      'Hydrolysed Keratin + Silk Proteins',
      'Rebuilds internal hair structure',
      'Eliminates breakage & split ends',
      'Restores elasticity and strength',
      'pH balanced formula',
      'Salon-quality results at home',
      '250ml bottle',
    ],
    inStock: true,
    weightKg: 0.55,
    rating: 4.9,
    reviews: 147,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['protein', 'keratin', 'repair', 'strengthening'],
  },
  {
    id: 'maint-004',
    name: 'Wig Care Starter Kit',
    slug: 'wig-care-starter-kit',
    category: 'maintenance',
    categoryLabel: 'Hair Maintenance',
    price: 55,
    originalPrice: 85,
    images: [
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'bestseller',
    shortDesc: 'Everything you need to care for your wigs. Complete kit.',
    description: 'The ultimate wig care bundle. Everything a new or experienced wig wearer needs to keep their wigs fresh, clean and beautiful. Specially formulated products that are gentle enough for human hair while delivering professional results.',
    features: [
      'Sulphate-free wig shampoo (200ml)',
      'Deep conditioning spray (150ml)',
      'Detangling wide-tooth comb',
      'Wig stand + brush',
      'Edge control gel (50g)',
      'Wig storage bag',
      'Complete care guide booklet',
    ],
    inStock: true,
    weightKg: 0.55,
    rating: 4.8,
    reviews: 264,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['kit', 'wig care', 'bundle', 'starter'],
  },

  // ── BEAUTY PRODUCTS ───────────────────────────────────────────────────────
  {
    id: 'beauty-001',
    name: 'Luxury Matte Lip Kit',
    slug: 'luxury-matte-lip-kit',
    category: 'beauty',
    categoryLabel: 'Beauty Products',
    price: 35,
    originalPrice: 55,
    images: [
      'https://images.unsplash.com/photo-1631214803994-e0d7ebb18d68?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'bestseller',
    shortDesc: '6 stunning matte shades. Long-lasting formula for African skin tones.',
    description: 'Our Luxury Matte Lip Kit is expertly formulated for deeper skin tones — the shades are specifically curated to complement and elevate melanin-rich complexions. Each lip colour delivers rich, saturated pigment that lasts 12+ hours.',
    features: [
      '6 curated shades for deep skin tones',
      '12-hour wear formula',
      'Includes matching lip liner',
      'Non-drying, comfortable wear',
      'Dermatologist tested',
      'Cruelty-free formula',
    ],
    variants: [
      { label: 'Shade Set', options: ['Nude Royale', 'Berry Queen', 'African Sunset', 'Deep Plum', 'Cocoa Dream', 'Full Set (All 6)'] },
    ],
    inStock: true,
    weightKg: 0.3,
    rating: 4.8,
    reviews: 389,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['lips', 'matte', 'lipstick', 'melanin'],
  },
  {
    id: 'beauty-002',
    name: 'Vitamin C Glow Serum',
    slug: 'vitamin-c-glow-serum',
    category: 'beauty',
    categoryLabel: 'Beauty Products',
    price: 42,
    images: [
      'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'hot',
    shortDesc: 'Brighten, even & glow. 20% Vitamin C powerhouse serum.',
    description: 'Formulated for melanin-rich skin, our Vitamin C Glow Serum combines 20% stabilised Vitamin C with Niacinamide and Hyaluronic Acid to brighten dark spots, even skin tone and deliver an enviable glow. Visible results in just 2 weeks.',
    features: [
      '20% Stabilised Vitamin C',
      'Niacinamide for even skin tone',
      'Hyaluronic Acid for deep hydration',
      'Fades dark spots & hyperpigmentation',
      'Suitable for all melanin skin tones',
      'Dermatologist tested',
      '30ml airless pump bottle',
    ],
    inStock: true,
    weightKg: 0.3,
    rating: 4.9,
    reviews: 276,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['serum', 'vitamin c', 'glow', 'brightening', 'skincare'],
  },
  {
    id: 'beauty-003',
    name: '24H Long-Wear Foundation',
    slug: '24h-long-wear-foundation',
    category: 'beauty',
    categoryLabel: 'Beauty Products',
    price: 38,
    originalPrice: 52,
    images: [
      'https://images.unsplash.com/photo-1631214803994-e0d7ebb18d68?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'sale',
    shortDesc: 'Full coverage, 24-hour wear. 40 shades for every queen.',
    description: 'Our 24H Long-Wear Foundation is a game changer — full coverage that doesn\'t feel heavy, stays fresh for 24 hours, and oxidises beautifully on deeper skin tones. SPF 30 protection built-in. 40 inclusive shades from fair to deep ebony.',
    features: [
      '40 inclusive shades',
      '24-hour wear formula',
      'SPF 30 protection',
      'Full coverage, natural finish',
      'Transfer-resistant',
      'Sweat & humidity proof',
    ],
    variants: [
      { label: 'Shade', options: ['N10', 'N20', 'N30', 'N40 (Medium)', 'N50', 'N60', 'N70 (Deep)', 'N80', 'N85', 'N90 (Deep Ebony)'] },
    ],
    inStock: true,
    weightKg: 0.3,
    rating: 4.7,
    reviews: 445,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['foundation', 'makeup', 'full coverage', 'inclusive'],
  },
  {
    id: 'beauty-004',
    name: 'HD Setting Spray & Primer Set',
    slug: 'hd-setting-spray-primer-set',
    category: 'beauty',
    categoryLabel: 'Beauty Products',
    price: 29,
    images: [
      'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'new',
    shortDesc: 'Lock your look all day. Primer + setting spray duo.',
    description: 'The perfect makeup longevity duo. Our HD Primer creates a smooth, pore-minimising base while the Setting Spray locks everything in place for 18+ hours. Both formulated to withstand the West African heat and humidity.',
    features: [
      'Primer + Setting Spray bundle',
      'Pore-minimising primer formula',
      '18-hour makeup lock technology',
      'Heat & humidity resistant',
      'Mist-fine spray for natural finish',
      '100ml each',
    ],
    inStock: true,
    weightKg: 0.3,
    rating: 4.8,
    reviews: 203,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['setting spray', 'primer', 'makeup', 'long lasting'],
  },

  // ── COATS ─────────────────────────────────────────────────────────────────
  {
    id: 'coat-001',
    name: 'Luxury Belted Wool Coat',
    slug: 'luxury-belted-wool-coat',
    category: 'coats',
    categoryLabel: 'Female Coats',
    price: 145,
    originalPrice: 210,
    images: [
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1520975867988-cd31f11e88b6?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'bestseller',
    shortDesc: 'Timeless elegance. Premium wool blend with flattering belt.',
    description: 'Command attention in our Luxury Belted Wool Coat. Crafted from a premium wool-cashmere blend, this coat drapes beautifully and cinches at the waist for a figure-flattering silhouette. The epitome of sophisticated femininity.',
    features: [
      '70% Wool / 30% Cashmere blend',
      'Flattering belted waist',
      'Double-breasted button front',
      'Lined interior for warmth',
      'Available in 3 classic colours',
      'Dry clean only',
    ],
    variants: [
      { label: 'Size', options: ['XS', 'S', 'M', 'L', 'XL', 'XXL'] },
      { label: 'Colour', options: ['Classic Camel', 'Jet Black', 'Ivory Cream'] },
    ],
    inStock: true,
    weightKg: 0.9,
    rating: 4.9,
    reviews: 178,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['coat', 'wool', 'belted', 'elegant'],
  },
  {
    id: 'coat-002',
    name: 'Premium Faux Leather Jacket',
    slug: 'premium-faux-leather-jacket',
    category: 'coats',
    categoryLabel: 'Female Coats',
    price: 98,
    images: [
      'https://images.unsplash.com/photo-1520975867988-cd31f11e88b6?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'hot',
    shortDesc: 'Edgy meets elegant. Premium vegan leather with gold hardware.',
    description: 'Our Premium Faux Leather Jacket brings edge and confidence to any outfit. High-quality vegan leather with luxurious gold-tone hardware perfectly complements the Taries Beauty aesthetic. Structured shoulders and slim cut for a powerful silhouette.',
    features: [
      'Premium PU Vegan Leather',
      'Gold-tone hardware & zips',
      'Structured shoulder design',
      'Fully lined interior',
      'Multiple pocket design',
      'Machine washable',
    ],
    variants: [
      { label: 'Size', options: ['XS', 'S', 'M', 'L', 'XL', 'XXL'] },
      { label: 'Colour', options: ['Jet Black', 'Deep Burgundy', 'Cognac Brown'] },
    ],
    inStock: true,
    weightKg: 0.9,
    rating: 4.7,
    reviews: 234,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['jacket', 'leather', 'vegan', 'edgy'],
  },
  {
    id: 'coat-003',
    name: 'Draped Satin Evening Coat',
    slug: 'draped-satin-evening-coat',
    category: 'coats',
    categoryLabel: 'Female Coats',
    price: 119,
    originalPrice: 160,
    images: [
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=800&q=80',
    ],
    badge: 'new',
    shortDesc: 'For the moments that matter. Luxurious satin drape coat.',
    description: 'Make an entrance with our Draped Satin Evening Coat. The fluid, lustrous satin drapes effortlessly over the body creating a glamorous silhouette perfect for galas, weddings and special occasions. A statement piece that demands attention.',
    features: [
      '100% Satin lining + exterior',
      'Fluid, draped silhouette',
      'Waterfall front design',
      'Three-quarter sleeves',
      'Occasion-ready look',
      'Available in 4 rich colours',
    ],
    variants: [
      { label: 'Size', options: ['XS', 'S', 'M', 'L', 'XL'] },
      { label: 'Colour', options: ['Champagne Gold', 'Midnight Black', 'Deep Wine', 'Forest Green'] },
    ],
    inStock: true,
    weightKg: 0.9,
    rating: 4.8,
    reviews: 112,
    shipsFrom: 'Guangzhou, China',
    deliveryDays: '7–14 business days',
    tags: ['satin', 'evening', 'occasion', 'glamour'],
  },
]

export const categories = [
  {
    id: 'wigs',
    label: 'Human Hair Wigs',
    description: 'Undetectable HD lace. 100% virgin human hair.',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
    count: products.filter(p => p.category === 'wigs').length,
    icon: '👑',
  },
  {
    id: 'bundles',
    label: 'Hair Bundles',
    description: 'Virgin hair bundles in every texture.',
    image: 'https://images.unsplash.com/photo-1522338140262-f46f5913618a?auto=format&fit=crop&w=600&q=80',
    count: products.filter(p => p.category === 'bundles').length,
    icon: '✨',
  },
  {
    id: 'custom-wigs',
    label: 'Custom Wigs',
    description: 'Handcrafted to your exact specifications.',
    image: 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=600&q=80',
    count: products.filter(p => p.category === 'custom-wigs').length,
    icon: '💎',
  },
  {
    id: 'maintenance',
    label: 'Hair Maintenance',
    description: 'Professional care for your tresses.',
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=600&q=80',
    count: products.filter(p => p.category === 'maintenance').length,
    icon: '🌿',
  },
  {
    id: 'beauty',
    label: 'Beauty Products',
    description: 'Celebrate your melanin. Glow differently.',
    image: 'https://images.unsplash.com/photo-1631214803994-e0d7ebb18d68?auto=format&fit=crop&w=600&q=80',
    count: products.filter(p => p.category === 'beauty').length,
    icon: '💄',
  },
  {
    id: 'coats',
    label: 'Female Coats',
    description: 'Elegance for every occasion.',
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=600&q=80',
    count: products.filter(p => p.category === 'coats').length,
    icon: '🧥',
  },
]

export const testimonials = [
  { id: 1, name: 'Adaeze Okafor', location: 'Lagos, Nigeria', rating: 5, text: 'I\'ve ordered from Taries 3 times now and every single wig has been absolutely flawless! The HD lace is undetectable. My clients keep asking where I get my hair from 😭❤️', avatar: 'AO', date: '2 weeks ago' },
  { id: 2, name: 'Abena Mensah', location: 'Accra, Ghana', rating: 5, text: 'The Brazilian body wave bundles are EVERYTHING. Zero shedding after 3 months of wear. Shipping was faster than expected too! Taries Beauty is a game changer.', avatar: 'AM', date: '1 month ago' },
  { id: 3, name: 'Chidinma Eze', location: 'Abuja, Nigeria', rating: 5, text: 'Ordered a custom wig and I am in tears at how beautiful it came out! They followed my instructions exactly. Worth every penny. The quality is 10/10', avatar: 'CE', date: '3 weeks ago' },
  { id: 4, name: 'Efua Boateng', location: 'Kumasi, Ghana', rating: 5, text: 'The Vitamin C serum cleared my dark spots in just 3 weeks! And the lip kit shades are PERFECT for my dark skin. Will be ordering the full skincare routine soon!', avatar: 'EB', date: '1 week ago' },
  { id: 5, name: 'Blessing Nwachukwu', location: 'Port Harcourt, Nigeria', rating: 5, text: 'Best luxury brand in West Africa. Full stop. The wool coat I got is absolutely stunning quality and fits like a dream. I\'ve gotten so many compliments!', avatar: 'BN', date: '2 months ago' },
  { id: 6, name: 'Akua Asante', location: 'Cape Coast, Ghana', rating: 5, text: 'Taries Beauty is my go-to for everything beauty. The wig care kit keeps my wigs looking brand new. Customer service is also super responsive on WhatsApp!', avatar: 'AA', date: '3 weeks ago' },
]
